data_sources:
  # Market Data from CSV
  market_data_csv:
    identifier: "MarketDataLoading"
    type: "csv"
    source:
      file_path: "src/main/resources/data/market/daily_rates.csv"
      delimiter: ","
      header: true
      encoding: "UTF-8"
    target:
      schema: "public"
      table: "market_trends"
      batch_size: 500
    column_mapping:
      - source: "date"
        target: "trade_date"
      - source: "currency_pair"
        target: "currency"
      - source: "rate"
        target: "exchange_rate"
      - source: "volume"
        target: "trading_volume"

  # Risk Metrics from Excel
  risk_metrics_excel:
    identifier: "RiskMetricsLoading"
    type: "excel"
    source:
      file_path: "src/main/resources/data/risk/monthly_risk.xlsx"
      sheet_name: "RiskData"
      skip_rows: 1
    target:
      schema: "public"
      table: "risk_metrics"
      batch_size: 200
    column_mapping:
      - source: "Portfolio ID"
        target: "portfolio_id"
      - source: "VaR 95%"
        target: "var_95"
      - source: "Expected Shortfall"
        target: "expected_shortfall"
      - source: "Liquidity Score"
        target: "liquidity_score"
    validation:
      required_columns: ["Portfolio ID", "VaR 95%"]
      data_quality_checks: true

  # API Data (Example - will need real endpoint)
  random_api:
    identifier: "RandomAPILoading"
    type: "rest_api"
    source:
      url: "https://jsonplaceholder.typicode.com/posts"
      method: "GET"
      headers:
        Content-Type: "application/json"
      timeout: 30
      retry_attempts: 3
    target:
      schema: "public"
      table: "forecast_data"
      batch_size: 1000
    column_mapping:
      - source: "id"
        target: "forecast_id"
      - source: "title"
        target: "asset_class"
      - source: "body"
        target: "predicted_liquidity"
      - source: "userId"
        target: "user_id"

  # JSON Configuration Files
  config_json:
    identifier: "JSONLoading"
    type: "json"
    source:
      file_path: "src/main/resources/data/config/portfolio_settings.json"
      json_path: "$[*]"
    target:
      schema: "public"
      table: "portfolio_config"
      batch_size: 100
    column_mapping:
      - source: "id"
        target: "portfolio_id"
      - source: "name"
        target: "portfolio_name"
      - source: "riskProfile"
        target: "risk_profile"
      - source: "liquidityThreshold"
        target: "liquidity_threshold"
